version: '3'
services:
  eks:
    build: .
    tty: true
    stdin_open: true
    environment:
      - AWS_REGION="ap-northeast-1"
      - LANG="ja_jp.UTF-8"
    volumes:
      - $HOME/.ssh:/root/.ssh